// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQSC1z50u-iT5G3OewCz0AsI6PZDbB1A',
    appId: '1:912544190164:web:44bfe17e20eed3594cf541',
    messagingSenderId: '912544190164',
    projectId: 'smart-classroom-app-ab2a3',
    authDomain: 'smart-classroom-app-ab2a3.firebaseapp.com',
    storageBucket: 'smart-classroom-app-ab2a3.firebasestorage.app',
    measurementId: 'G-F61X8ZJS0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKcTen-2lgFz3uzSFOsgbyeWRCzmLM-U',
    appId: '1:912544190164:android:e9f6bc44288b8ac74cf541',
    messagingSenderId: '912544190164',
    projectId: 'smart-classroom-app-ab2a3',
    storageBucket: 'smart-classroom-app-ab2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxrkf7swYbs0HFFKXFLr6a7bVzj99_UE',
    appId: '1:912544190164:ios:d492340117821dd54cf541',
    messagingSenderId: '912544190164',
    projectId: 'smart-classroom-app-ab2a3',
    storageBucket: 'smart-classroom-app-ab2a3.firebasestorage.app',
    iosBundleId: 'com.smartclassroom.smartClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNxrkf7swYbs0HFFKXFLr6a7bVzj99_UE',
    appId: '1:912544190164:ios:d492340117821dd54cf541',
    messagingSenderId: '912544190164',
    projectId: 'smart-classroom-app-ab2a3',
    storageBucket: 'smart-classroom-app-ab2a3.firebasestorage.app',
    iosBundleId: 'com.smartclassroom.smartClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATQSC1z50u-iT5G3OewCz0AsI6PZDbB1A',
    appId: '1:912544190164:web:ed84f7385f46bf7f4cf541',
    messagingSenderId: '912544190164',
    projectId: 'smart-classroom-app-ab2a3',
    authDomain: 'smart-classroom-app-ab2a3.firebaseapp.com',
    storageBucket: 'smart-classroom-app-ab2a3.firebasestorage.app',
    measurementId: 'G-9BNHXMJH16',
  );
}
